###########################################################
# Copyright (c) 2023 Johannes G. Arlt - Berlin - Germany
# License MIT License
# -----
# File: /.pre-commit-config.yaml
# Project: uxaWiFiManager
# Description: 
# -----
# Created Date: 2023-08-28 19:36
# Author: Johannes G.  Arlt (janusz)
# -----
# Last Modified:
# Modified By:
###########################################################



# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

# run ```pre-commit run --all-files``` to run tests without git
# run with ```--no-verify```  to disable tests if invoked by git

fail_fast: false

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-added-large-files
    args: ['--maxkb=2048']
  - id: check-case-conflict
  - id: check-executables-have-shebangs
  - id: check-symlinks
  - id: fix-byte-order-marker
  - id: detect-private-key
  - id: mixed-line-ending
  - id: check-merge-conflict
  - id: forbid-submodules
  - id: check-byte-order-marker
  - id: check-json
  - id: pretty-format-json
  - id: check-toml
  - id: check-xml
  - id: check-yaml
  - id: end-of-file-fixer

- repo: https://github.com/pre-commit/mirrors-jshint
  rev: v2.13.6
  hooks:
  - id: jshint

- repo: https://github.com/pre-commit/mirrors-fixmyjs
  rev: v2.0.0
  hooks:
  - id: fixmyjs

- repo: https://github.com/Lucas-C/pre-commit-hooks-lxml
  rev: v1.1.0
  hooks:
  - id: detect-missing-css-classes
    args:
    - --css-files-dir=data
    - --html-files-dir=data
  - id: forbid-html-img-without-alt-text
  # - id: forbid-non-std-html-attributes
  - id: html-tags-blacklist
  - id: html-attributes-blacklist

- repo: https://github.com/pre-commit/mirrors-csslint
  rev: v1.0.5
  hooks:
  - id: csslint

#-   repo: https://github.com/Lucas-C/pre-commit-hooks-java
#    rev: master
#    hooks:
#    -   id: validate-html

- repo: https://github.com/bmorcos/pre-commit-hooks-cpp
  rev: 9a5aa38207bf557961110d6a4f7e3a9d352911f9
  hooks:

  - id: clang-format
    exclude: (^attic|^build|^doc)
    # LLVM, GNU, Google, Chromium, Microsoft, Mozilla, WebKit
    args: [-style=Google]

  # - id: cpplint
  #   exclude: (^attic|^build|^doc)
  #   args: [
  #     --filter=-build/include_subdir
  #   ]

  - id: cppcheck
    exclude: (^attic|^build|^doc)
    args: [--language=c++,--inline-suppr]


# - repo: https://gitlab.com/massimocannavo/pre-commit-hooks
#   rev: 1.0.2
#   hooks:
#     - id: flawfinder
#       # args:
#       #   - --error-level=3
#       #   - --minlevel=3


- repo: local
  hooks:
  - id: compile
    name: test compile
    description: check if sources can compiled
    entry: platformio run --environment esp32
    pass_filenames: false
    language: system
#  - id: TODO
#    name: TODO Fixer
#    entry: .todo-checker
#    exclude: (^attic|^build|^doc)
#    types: [file]
#    language: script
